# Generated by Django 3.0.8 on 2020-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
